### ISSUE TITLE
How to install PigPIO

### ISSUE THREAD

**Issue by franfrandev** [farfalleflickan/OctoPrint-Hardwarepwm#1]
Hello!
I would like to control a Servo using your plugin, but I don't understand how to install pigpio.
Sorry for this, I'm a beginner .....
Have a nice day

**Comment by farfalleflickan** [comment]
Hi!
Octoprint takes care of that for you, it always installs any required dependencies, so no worries there :)

**Comment by franfrandev** [comment]
Okay, nice!
I would like to control 2 servos using the octoprint. So I first tried with a python program:

```
#!/usr/bin/env` python3
#-- coding: utf-8 --
import RPi.GPIO as GPIO
import time


#Set function to calculate percent from angle
def angle_to_percent (angle) :
    if angle > 180 or angle < 0 :
        return False

    start = 4
    end = 12.5
    ratio = (end - start)/180 #Calcul ratio from angle to percent

    angle_as_percent = angle * ratio

    return start + angle_as_percent


GPIO.setmode(GPIO.BOARD) #Use Board numerotation mode
GPIO.setwarnings(False) #Disable warnings

#Use pin 12 for PWM signal
pwm_gpio = 12
frequence = 50
GPIO.setup(pwm_gpio, GPIO.OUT)
pwm = GPIO.PWM(pwm_gpio, frequence)

#Init at 0°
pwm.start(angle_to_percent(0))
time.sleep(1)

#Go at 90°
pwm.ChangeDutyCycle(angle_to_percent(90))
time.sleep(1)

#Finish at 180°
pwm.ChangeDutyCycle(angle_to_percent(180))
time.sleep(1)

#Close GPIO & cleanup
pwm.stop()
GPIO.cleanup()
```

and it worked perfectly.
But the thing is that with the same servo, on the same pin (that I've selected in Octoprint), and same frequency, it won't move

**Comment by farfalleflickan** [comment]
This is because you are using the GPIO.BOARD mode/naming scheme. 
The plugin is in BCM mode, so to have the same behaviour you want to use pin 18 in the plugin ( which would then correspond to the 12 in the script ).
