### ISSUE TITLE
PIGPIO

### ISSUE THREAD

**Issue by FredGenius** [farfalleflickan/OctoPrint-Hardwarepwm#3]
I've installed the plugin, but I'm still getting flickering (PWM LED on BCM 17).  Says 'Requires you to install pigpio through apt-get and to start/enable the pigpiod daemon' - Can you explain how to do this please?

**Comment by farfalleflickan** [comment]
Hi!

Which board are you using? Pin 17 isn't a PWM pin, see [here](https://pinout.xyz/pinout/pwm#). The plugin supports only the hardware pins, which are pin 12, 13, 18 and 19.
You have to SSH into your Octoprint server (see the instructions [here](https://octoprint.org/download/)) and then follow [these](https://gist.github.com/tstellanova/8b1fb350a148eace6541b5fbd2c021ca) instructions.

**Comment by FredGenius** [comment]
Ok, I got it, thanks. Maybe include this info on the plugin summary page?

 

Fred Ö¿Ö
