### ISSUE TITLE
Multiple GPI0

### ISSUE THREAD

**Issue by ahmaddxb** [farfalleflickan/OctoPrint-Hardwarepwm#4]
Is it possable to control more than one pin at a time?

**Comment by farfalleflickan** [comment]
Hi @ahmaddxb!

I've updated the plugin, please report back if you have any issues :)

**Comment by thejiral** [comment]
I updated the plugin and now it is completely broken. I see the 4 pins and duty cycle but in the settings all options are gone and also just those duty cycles shown. Additionally, nothing seems to have changed. The Pi still sends the previously set PWM signal to my fan it seems as their speed hasn't changed.

**Comment by thejiral** [comment]
Could it be that before this update the PWM plugin remembered the Duty Cycle setting and now one has to set it at each start again, as only the frequency setting gets saved? It would be really helpful if the plugin kept the settings even beyond restarts as it apparently has done previously.

**Comment by farfalleflickan** [comment]
Thanks for the report, I had made a silly mistake and it's now fixed :) 

Sorry the update wasn't tested thoroughly, as I don't have the hardware at the moment, so let me know if you notice anything else not behaving properly.
