### ISSUE TITLE
Update available.

### ISSUE THREAD

**Issue by piotrenewicz** [farfalleflickan/OctoPrint-Hardwarepwm#5]
Octoprint detects an update for this plugin.
Plugin version in octoprint reads 0.2.1
Github states the newest version is v2.1
Performing the update, and rebooting...
Doesn't change any version numbers and makes this update detected again.
Ignoring the update, makes the update detected again later.

![Screenshot from 2021-09-19 13-48-28](https://user-images.githubusercontent.com/35681417/133926395-905f787e-1b10-4c8a-aa88-8f2a36f6c342.png)

**Comment by farfalleflickan** [comment]
Thank you for noticing this! I made a typo in the github release... Fixed now, octoprint should stop bothering you.
